# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupperson',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
