# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_groupperson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupperson',
            name='id',
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
