# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0003_auto_20171117_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='number_phone',
        ),
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.IntegerField(choices=[(1, 'home'), (2, 'business')], default=1),
        ),
    ]
