# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0004_auto_20171117_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupperson',
            name='name',
        ),
        migrations.AddField(
            model_name='groupperson',
            name='id',
            field=models.IntegerField(default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
