# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_book', '0002_auto_20171123_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPerson',
            fields=[
                ('id', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.Person')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='person',
            field=models.ManyToManyField(through='group.GroupPerson', to='address_book.Person'),
        ),
    ]
