# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='alias',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='secret_key',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
