# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20171116_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
    ]
