# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_remove_pizza_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(choices=[('h', 'half'), ('n', 'normal'), ('d', 'double'), ('t', 'triple')], default='n', max_length=1)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Pizza')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Topping')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(through='edu.PizzaTops', to='edu.Topping'),
        ),
    ]
