# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20171116_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaTops',
            new_name='PizzaTopps',
        ),
    ]
